# Nome lógico da aplicação dentro do Spring Boot.
spring.application.name=pix-security-api

# Perfil ativo: faz o Spring carregar também o arquivo application-local.properties.
spring.profiles.active=local

# Porta HTTP em que a API será executada.
server.port=8080
